name: Addon checker and unit testing in python

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: setup-micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: tests/envs/test.yml
        environment-name: python-test-env
        cache-environment: true
        post-cleanup: 'all'

    - name: Lint with ruff
      shell: bash -l {0}
      run: |
        ruff check .

    - name: Test with kodi-addon-checker
      shell: bash -l {0}
      run: |
        kodi-addon-checker --branch=nexus --allow-folder-id-mismatch
        kodi-addon-checker --branch=omega --allow-folder-id-mismatch

    - name: Unit tests
      shell: bash -l {0}
      run: |
        pytest tests --disable-warnings
