name: Addon checker and unit testing in python

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3

    - name: setup-micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: tests/envs/test.yml
        environment-name: python-test-env
        cache-environment: true
        post-cleanup: 'all'

    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82,E501,E722 --max-line=200 --show-source --statistics

 
    - name: Test with kodi-addon-checker
      shell: bash -l {0}
      run: |
        kodi-addon-checker --branch=matrix --allow-folder-id-mismatch

    - name: Unit tests
      shell: bash -l {0}
      run: |
        pytest tests --disable-warnings
